### ISSUE TITLE
Plugin doesn't support 1.17

### ISSUE THREAD

**Issue by ms0ur** [MultiCoreNetwork/VanillaTowns#1]
Purpur 1.17
Java 16
CentOs 7

Server thread/ERROR]: Error occurred while enabling VanillaTowns v1.3.0 (Is it up to date?)
java.lang.NumberFormatException: For input string: "17-R0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:660) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:778) ~[?:?]
	at it.multicoredev.vt.mbcore.spigot.Chat.translateHex(Chat.java:46) ~[?:?]
	at it.multicoredev.vt.mbcore.spigot.Chat.getTranslated(Chat.java:69) ~[?:?]
	at it.multicoredev.vt.mbcore.spigot.Chat.severe(Chat.java:416) ~[?:?]
	at it.multicoredev.vt.VanillaTowns.onEnable(VanillaTowns.java:53) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Purpur-1255]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Purpur-1255]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Purpur-1255]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Purpur-1255]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Purpur-1255]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:716) ~[patched_1.17.jar:git-Purpur-1255]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:315) ~[patched_1.17.jar:git-Purpur-1255]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1193) ~[patched_1.17.jar:git-Purpur-1255]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[patched_1.17.jar:git-Purpur-1255]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by LoreSchaeffer** [comment]
We just pushed an update on spigot to add 1.17.x compatibility. Please update the plugin and the error will disappear.
